//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testinator.UICore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testinator.UICore.Localization.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Answer.
        /// </summary>
        public static string AddAnswerButton {
            get {
                return ResourceManager.GetString("AddAnswerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the question task and every answer and check which of them are right..
        /// </summary>
        public static string AddMultipleCheckboxesQuestionIntroduction {
            get {
                return ResourceManager.GetString("AddMultipleCheckboxesQuestionIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the question task and every answer and check which one is right..
        /// </summary>
        public static string AddMultipleChoiceQuestionIntroduction {
            get {
                return ResourceManager.GetString("AddMultipleChoiceQuestionIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new question.
        /// </summary>
        public static string AddNewQuestion {
            get {
                return ResourceManager.GetString("AddNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the question task and an answer which is correct..
        /// </summary>
        public static string AddSingleTextboxQuestionIntroduction {
            get {
                return ResourceManager.GetString("AddSingleTextboxQuestionIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach criteria to the test.
        /// </summary>
        public static string AttachCriteriaTitle {
            get {
                return ResourceManager.GetString("AttachCriteriaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to test editor.
        /// </summary>
        public static string BackToTestEditor {
            get {
                return ResourceManager.GetString("BackToTestEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to test list.
        /// </summary>
        public static string BackToTestList {
            get {
                return ResourceManager.GetString("BackToTestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose question type.
        /// </summary>
        public static string ChooseQuestionType {
            get {
                return ResourceManager.GetString("ChooseQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new criteria.
        /// </summary>
        public static string CreateNewCriteria {
            get {
                return ResourceManager.GetString("CreateNewCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new criteria or edit existing one.
        /// </summary>
        public static string CreateNewCriteriaOrEditExisting {
            get {
                return ResourceManager.GetString("CreateNewCriteriaOrEditExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new test.
        /// </summary>
        public static string CreateNewTest {
            get {
                return ResourceManager.GetString("CreateNewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit criteria.
        /// </summary>
        public static string EditCriteria {
            get {
                return ResourceManager.GetString("EditCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit test.
        /// </summary>
        public static string EditTest {
            get {
                return ResourceManager.GetString("EditTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the data.
        /// </summary>
        public static string FillData {
            get {
                return ResourceManager.GetString("FillData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish question adding.
        /// </summary>
        public static string FinishQuestionAdding {
            get {
                return ResourceManager.GetString("FinishQuestionAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test informations.
        /// </summary>
        public static string InfoAboutTest {
            get {
                return ResourceManager.GetString("InfoAboutTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data in inputs..
        /// </summary>
        public static string InvalidDataError {
            get {
                return ResourceManager.GetString("InvalidDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Mark A?.
        /// </summary>
        public static string IsMarkACountedQuestion {
            get {
                return ResourceManager.GetString("IsMarkACountedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade A.
        /// </summary>
        public static string MarkAName {
            get {
                return ResourceManager.GetString("MarkAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade B.
        /// </summary>
        public static string MarkBName {
            get {
                return ResourceManager.GetString("MarkBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade C.
        /// </summary>
        public static string MarkCName {
            get {
                return ResourceManager.GetString("MarkCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade D.
        /// </summary>
        public static string MarkDName {
            get {
                return ResourceManager.GetString("MarkDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade E.
        /// </summary>
        public static string MarkEName {
            get {
                return ResourceManager.GetString("MarkEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade F.
        /// </summary>
        public static string MarkFName {
            get {
                return ResourceManager.GetString("MarkFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max points: .
        /// </summary>
        public static string MaxPointsTitle {
            get {
                return ResourceManager.GetString("MaxPointsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple checkboxes question.
        /// </summary>
        public static string MultipleCheckboxesQuestion {
            get {
                return ResourceManager.GetString("MultipleCheckboxesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice question.
        /// </summary>
        public static string MultipleChoiceQuestion {
            get {
                return ResourceManager.GetString("MultipleChoiceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next question.
        /// </summary>
        public static string NextQuestion {
            get {
                return ResourceManager.GetString("NextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points: .
        /// </summary>
        public static string PointsCount {
            get {
                return ResourceManager.GetString("PointsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: .
        /// </summary>
        public static string PointsSemicolon {
            get {
                return ResourceManager.GetString("PointsSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions: .
        /// </summary>
        public static string QuestionCount {
            get {
                return ResourceManager.GetString("QuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results.
        /// </summary>
        public static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightAnswer: .
        /// </summary>
        public static string RightAnswerSemicolon {
            get {
                return ResourceManager.GetString("RightAnswerSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the question.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the test.
        /// </summary>
        public static string SaveTest {
            get {
                return ResourceManager.GetString("SaveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test.
        /// </summary>
        public static string SendTest {
            get {
                return ResourceManager.GetString("SendTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single answer question.
        /// </summary>
        public static string SingleTextboxQuestion {
            get {
                return ResourceManager.GetString("SingleTextboxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User writes an answer in the textbox.
        /// </summary>
        public static string SingleTextboxQuestionTooltip {
            get {
                return ResourceManager.GetString("SingleTextboxQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start test.
        /// </summary>
        public static string StartTest {
            get {
                return ResourceManager.GetString("StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the test!.
        /// </summary>
        public static string SuccessfulTestAdd {
            get {
                return ResourceManager.GetString("SuccessfulTestAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for test [min].
        /// </summary>
        public static string TestDurationInMinutes {
            get {
                return ResourceManager.GetString("TestDurationInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Editor.
        /// </summary>
        public static string TestEditorTitle {
            get {
                return ResourceManager.GetString("TestEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the test.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a test!.
        /// </summary>
        public static string TestReceivedMessage {
            get {
                return ResourceManager.GetString("TestReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        public static string TimeDuration {
            get {
                return ResourceManager.GetString("TimeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input values are counted in %: .
        /// </summary>
        public static string ValuesCountedInPercent {
            get {
                return ResourceManager.GetString("ValuesCountedInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection with server.
        /// </summary>
        public static string WaitingForConnection {
            get {
                return ResourceManager.GetString("WaitingForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the test.
        /// </summary>
        public static string WaitingForTest {
            get {
                return ResourceManager.GetString("WaitingForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write name.
        /// </summary>
        public static string WriteName {
            get {
                return ResourceManager.GetString("WriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your username.
        /// </summary>
        public static string WriteUsername {
            get {
                return ResourceManager.GetString("WriteUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your Surname.
        /// </summary>
        public static string WriteUserSurname {
            get {
                return ResourceManager.GetString("WriteUserSurname", resourceCulture);
            }
        }
    }
}
