//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testinator.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testinator.Core.Localization.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting.
        /// </summary>
        public static string Aborting {
            get {
                return ResourceManager.GetString("Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Answer.
        /// </summary>
        public static string AddAnswerButton {
            get {
                return ResourceManager.GetString("AddAnswerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add latecomers.
        /// </summary>
        public static string AddLatecomers {
            get {
                return ResourceManager.GetString("AddLatecomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the question task and every answer and check which of them are right..
        /// </summary>
        public static string AddMultipleCheckboxesQuestionIntroduction {
            get {
                return ResourceManager.GetString("AddMultipleCheckboxesQuestionIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the question task and every answer and check which one is right..
        /// </summary>
        public static string AddMultipleChoiceQuestionIntroduction {
            get {
                return ResourceManager.GetString("AddMultipleChoiceQuestionIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new question.
        /// </summary>
        public static string AddNewQuestion {
            get {
                return ResourceManager.GetString("AddNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the question task and an answer which is correct..
        /// </summary>
        public static string AddSingleTextboxQuestionIntroduction {
            get {
                return ResourceManager.GetString("AddSingleTextboxQuestionIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of points.
        /// </summary>
        public static string AmountOfPoints {
            get {
                return ResourceManager.GetString("AmountOfPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach criteria to the test.
        /// </summary>
        public static string AttachCriteriaTitle {
            get {
                return ResourceManager.GetString("AttachCriteriaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to test editor.
        /// </summary>
        public static string BackToTestEditor {
            get {
                return ResourceManager.GetString("BackToTestEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to test list.
        /// </summary>
        public static string BackToTestList {
            get {
                return ResourceManager.GetString("BackToTestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen criteria will be deleted..
        /// </summary>
        public static string ChoosenCriteriaWillBeDeleted {
            get {
                return ResourceManager.GetString("ChoosenCriteriaWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose question type.
        /// </summary>
        public static string ChooseQuestionType {
            get {
                return ResourceManager.GetString("ChooseQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to show more info.
        /// </summary>
        public static string ChooseToShow {
            get {
                return ResourceManager.GetString("ChooseToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm changes.
        /// </summary>
        public static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection falied.
        /// </summary>
        public static string ConnectionFalied {
            get {
                return ResourceManager.GetString("ConnectionFalied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string ContinueQuestion {
            get {
                return ResourceManager.GetString("ContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the data.
        /// </summary>
        public static string CouldNotSendData {
            get {
                return ResourceManager.GetString("CouldNotSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the server!.
        /// </summary>
        public static string CouldNotStartServer {
            get {
                return ResourceManager.GetString("CouldNotStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new criteria.
        /// </summary>
        public static string CreateNewCriteria {
            get {
                return ResourceManager.GetString("CreateNewCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new criteria or edit existing one.
        /// </summary>
        public static string CreateNewCriteriaOrEditExisting {
            get {
                return ResourceManager.GetString("CreateNewCriteriaOrEditExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new test.
        /// </summary>
        public static string CreateNewTest {
            get {
                return ResourceManager.GetString("CreateNewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new PIN.
        /// </summary>
        public static string CreatePIN {
            get {
                return ResourceManager.GetString("CreatePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria deletion.
        /// </summary>
        public static string CriteriaDeletion {
            get {
                return ResourceManager.GetString("CriteriaDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria edited.
        /// </summary>
        public static string CriteriaEdited {
            get {
                return ResourceManager.GetString("CriteriaEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria are being edited right now, page change will discard all changes..
        /// </summary>
        public static string CriteriaEditedPageChangeDiscardChanges {
            get {
                return ResourceManager.GetString("CriteriaEditedPageChangeDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string DateSemicolon {
            get {
                return ResourceManager.GetString("DateSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete test.
        /// </summary>
        public static string DeleteTest {
            get {
                return ResourceManager.GetString("DeleteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion error.
        /// </summary>
        public static string DeletionError {
            get {
                return ResourceManager.GetString("DeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit criteria.
        /// </summary>
        public static string EditCriteria {
            get {
                return ResourceManager.GetString("EditCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit test.
        /// </summary>
        public static string EditTest {
            get {
                return ResourceManager.GetString("EditTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message: .
        /// </summary>
        public static string ErrorContentSemicolon {
            get {
                return ResourceManager.GetString("ErrorContentSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the data.
        /// </summary>
        public static string FillData {
            get {
                return ResourceManager.GetString("FillData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill your PIN.
        /// </summary>
        public static string FillPIN {
            get {
                return ResourceManager.GetString("FillPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish test before time runs out.
        /// </summary>
        public static string FinishBeforeTime {
            get {
                return ResourceManager.GetString("FinishBeforeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish question adding.
        /// </summary>
        public static string FinishQuestionAdding {
            get {
                return ResourceManager.GetString("FinishQuestionAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test informations.
        /// </summary>
        public static string InfoAboutTest {
            get {
                return ResourceManager.GetString("InfoAboutTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data in inputs..
        /// </summary>
        public static string InvalidDataError {
            get {
                return ResourceManager.GetString("InvalidDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Mark A?.
        /// </summary>
        public static string IsMarkACountedQuestion {
            get {
                return ResourceManager.GetString("IsMarkACountedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded: .
        /// </summary>
        public static string LoadedSemicolon {
            get {
                return ResourceManager.GetString("LoadedSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading error.
        /// </summary>
        public static string LoadingError {
            get {
                return ResourceManager.GetString("LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade A.
        /// </summary>
        public static string MarkAName {
            get {
                return ResourceManager.GetString("MarkAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade B.
        /// </summary>
        public static string MarkBName {
            get {
                return ResourceManager.GetString("MarkBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade C.
        /// </summary>
        public static string MarkCName {
            get {
                return ResourceManager.GetString("MarkCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade D.
        /// </summary>
        public static string MarkDName {
            get {
                return ResourceManager.GetString("MarkDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade E.
        /// </summary>
        public static string MarkEName {
            get {
                return ResourceManager.GetString("MarkEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade F.
        /// </summary>
        public static string MarkFName {
            get {
                return ResourceManager.GetString("MarkFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of attempts has beed reached. \nTry again or make sure the server is online..
        /// </summary>
        public static string MaximumAttemptsReachedMessage {
            get {
                return ResourceManager.GetString("MaximumAttemptsReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max points: .
        /// </summary>
        public static string MaxPointsTitle {
            get {
                return ResourceManager.GetString("MaxPointsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple checkboxes question.
        /// </summary>
        public static string MultipleCheckboxesQuestion {
            get {
                return ResourceManager.GetString("MultipleCheckboxesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice question.
        /// </summary>
        public static string MultipleChoiceQuestion {
            get {
                return ResourceManager.GetString("MultipleChoiceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New important update!.
        /// </summary>
        public static string NewImportantUpdate {
            get {
                return ResourceManager.GetString("NewImportantUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New important update is up and ready to download, application will close..
        /// </summary>
        public static string NewImportantUpdateInfo {
            get {
                return ResourceManager.GetString("NewImportantUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update found!.
        /// </summary>
        public static string NewUpdate {
            get {
                return ResourceManager.GetString("NewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of Testinator can be downloaded, update now?.
        /// </summary>
        public static string NewVersionCanDownload {
            get {
                return ResourceManager.GetString("NewVersionCanDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next question.
        /// </summary>
        public static string NextQuestion {
            get {
                return ResourceManager.GetString("NextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test has been choosen yet!.
        /// </summary>
        public static string NoTestChoosen {
            get {
                return ResourceManager.GetString("NoTestChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users connected yet!.
        /// </summary>
        public static string NoUsersConnected {
            get {
                return ResourceManager.GetString("NoUsersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points: .
        /// </summary>
        public static string PointsCount {
            get {
                return ResourceManager.GetString("PointsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: .
        /// </summary>
        public static string PointsSemicolon {
            get {
                return ResourceManager.GetString("PointsSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided PIN is not valid..
        /// </summary>
        public static string ProvidedPINNotValid {
            get {
                return ResourceManager.GetString("ProvidedPINNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions: .
        /// </summary>
        public static string QuestionCount {
            get {
                return ResourceManager.GetString("QuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions view.
        /// </summary>
        public static string QuestionsView {
            get {
                return ResourceManager.GetString("QuestionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated PIN is not the same as the original..
        /// </summary>
        public static string RepeatedPINNotSame {
            get {
                return ResourceManager.GetString("RepeatedPINNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat PIN.
        /// </summary>
        public static string RepeatPIN {
            get {
                return ResourceManager.GetString("RepeatPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results were saved..
        /// </summary>
        public static string ResultsSaved {
            get {
                return ResourceManager.GetString("ResultsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results.
        /// </summary>
        public static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightAnswer: .
        /// </summary>
        public static string RightAnswerSemicolon {
            get {
                return ResourceManager.GetString("RightAnswerSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the question.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the test.
        /// </summary>
        public static string SaveTest {
            get {
                return ResourceManager.GetString("SaveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving error.
        /// </summary>
        public static string SavingError {
            get {
                return ResourceManager.GetString("SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen stream.
        /// </summary>
        public static string ScreenStream {
            get {
                return ResourceManager.GetString("ScreenStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test.
        /// </summary>
        public static string SendTest {
            get {
                return ResourceManager.GetString("SendTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the test?.
        /// </summary>
        public static string SendTestQuestion {
            get {
                return ResourceManager.GetString("SendTestQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server status.
        /// </summary>
        public static string ServerStatus {
            get {
                return ResourceManager.GetString("ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show right answers.
        /// </summary>
        public static string ShowRightAnswers {
            get {
                return ResourceManager.GetString("ShowRightAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single answer question.
        /// </summary>
        public static string SingleTextboxQuestion {
            get {
                return ResourceManager.GetString("SingleTextboxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User writes an answer in the textbox.
        /// </summary>
        public static string SingleTextboxQuestionTooltip {
            get {
                return ResourceManager.GetString("SingleTextboxQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip update.
        /// </summary>
        public static string SkipUpdate {
            get {
                return ResourceManager.GetString("SkipUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes were unsaved..
        /// </summary>
        public static string SomeChangesWereUnsaved {
            get {
                return ResourceManager.GetString("SomeChangesWereUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  results..
        /// </summary>
        public static string SpaceResults {
            get {
                return ResourceManager.GetString("SpaceResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start test.
        /// </summary>
        public static string StartTest {
            get {
                return ResourceManager.GetString("StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the test.
        /// </summary>
        public static string StopTest {
            get {
                return ResourceManager.GetString("StopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the test!.
        /// </summary>
        public static string SuccessfulTestAdd {
            get {
                return ResourceManager.GetString("SuccessfulTestAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure.
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users taking part.
        /// </summary>
        public static string TakingPart {
            get {
                return ResourceManager.GetString("TakingPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task: .
        /// </summary>
        public static string TaskSemicolon {
            get {
                return ResourceManager.GetString("TaskSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for test [min].
        /// </summary>
        public static string TestDurationInMinutes {
            get {
                return ResourceManager.GetString("TestDurationInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Editor.
        /// </summary>
        public static string TestEditorTitle {
            get {
                return ResourceManager.GetString("TestEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the test.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a test!.
        /// </summary>
        public static string TestReceivedMessage {
            get {
                return ResourceManager.GetString("TestReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results.
        /// </summary>
        public static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: .
        /// </summary>
        public static string TestSemicolon {
            get {
                return ResourceManager.GetString("TestSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        public static string TimeDuration {
            get {
                return ResourceManager.GetString("TimeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try: .
        /// </summary>
        public static string TrySemicolon {
            get {
                return ResourceManager.GetString("TrySemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete choosen criteria..
        /// </summary>
        public static string UnableToDeleteCriteria {
            get {
                return ResourceManager.GetString("UnableToDeleteCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the config file..
        /// </summary>
        public static string UnableToLoadConfigFile {
            get {
                return ResourceManager.GetString("UnableToLoadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save new value to the config file..
        /// </summary>
        public static string UnableToSaveConfigFile {
            get {
                return ResourceManager.GetString("UnableToSaveConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save current criteria..
        /// </summary>
        public static string UnableToSaveCurrentCriteria {
            get {
                return ResourceManager.GetString("UnableToSaveCurrentCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users view.
        /// </summary>
        public static string UsersView {
            get {
                return ResourceManager.GetString("UsersView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input values are counted in %: .
        /// </summary>
        public static string ValuesCountedInPercent {
            get {
                return ResourceManager.GetString("ValuesCountedInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection with server.
        /// </summary>
        public static string WaitingForConnection {
            get {
                return ResourceManager.GetString("WaitingForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the test.
        /// </summary>
        public static string WaitingForTest {
            get {
                return ResourceManager.GetString("WaitingForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write name.
        /// </summary>
        public static string WriteName {
            get {
                return ResourceManager.GetString("WriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your username.
        /// </summary>
        public static string WriteUsername {
            get {
                return ResourceManager.GetString("WriteUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your Surname.
        /// </summary>
        public static string WriteUserSurname {
            get {
                return ResourceManager.GetString("WriteUserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
